### PR TITLE
support for aeson 2

### PR DESCRIPTION
**Pull request by avieth**
also set version to 0.5, since old aesons are not supported

### CODE REVIEW

**Comment by jpvillaisaza** [comment]
Thanks!

Looks like the Stack resolvers used for CI need to be updated as well. I can take a look at that later this week.

**Comment by jpvillaisaza** [comment]
Sorry, I got sick and haven't been able to review this yet.

**Comment by parsonsmatt** [comment]
Anything we can do to help get this merged?

re CI, I've had a good time using `haskell-ci` and GitHub Actions. Works nicely: https://github.com/haskell-CI/haskell-ci

**Comment by jpvillaisaza** [comment]
I merged the change and opened an issue to update CI.

Sorry it took so long. I'm actually looking to transfer ownership of this library, or to have someone else to maintain it since I'm not currently using it anywhere. I had already talked to someone about this, but I'll try to get confirmation. Also posting here if someone else is interested.

**Pull request merged**
