### PR TITLE
relax dependencies, use newer stackage snapshot

### PR DESCRIPTION
**Pull request by emmanueltouzery**
relax dependencies, use newer stackage snapshot.

i would also be interested to maintain slack-web on stackage, if you don't have the time. i already have two packages on hackage, so I could also upload it hackage, which would be needed to be able to maintain it on stackage. the question, is do you think it's a good idea?

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
hmm CI fails because we need stack 1.5.1 as this is ghc 8.2.1 now. now sure where circleCI gets its stack.

**EDIT** fixed it by overwriting circleci's default stack by a newer one.

**Comment by jpvillaisaza** [comment]
@emmanueltouzery Great! Running `stack upgrade` should work too to update CircleCI's preinstalled version (1.4.0).

About Hackage and Stackage, yes. I haven't added to Stackage since I'm not currently using the library and it wasn't ready, but yes. What is your Hackage username? I can add you as maintainer so you can upload new versions.

**Comment by emmanueltouzery** [comment]
you're right about `stack upgrade` of course :-) I changed it to do that. It does work.

great about hackage/stackage :-) my hackage username is `EmmanuelTouzery`.

I do use slack-web in a little app of mine: https://github.com/emmanueltouzery/cigale-timesheet -- I'm the sole user but I do use it all the time, so it gives me motive enough to keep it working :-)

**Comment by jpvillaisaza** [comment]
@emmanueltouzery Okay, I added you as maintainer (https://hackage.haskell.org/package/slack-web/maintainers/), so you can upload new versions and add to Stackage.

**Pull request merged**
